name: Merge main into develop

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  SRC_BRANCH: main
  TGT_BRANCH: develop

jobs:
  main:
    name: Merge main into develop
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CREDOAIBOT_TOKEN }}
          ref: refs/heads/main
          fetch-depth: 0

      - name: perform merge
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git status
          git pull
          git checkout "$TGT_BRANCH"
          git status
          git merge "$SRC_BRANCH" --no-edit
          git push
          git status
