name: Test

on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.ipynb'

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          set -o pipefail
          scripts/test.sh | tee ./pytest-coverage.txt
      - name: my-artifact
        if: always() && !env.ACT
        uses: actions/upload-artifact@v3
        with:
          name: pytest-coverage
          path: pytest-coverage.txt
      - name: Pytest coverage comment
        if: always() && !env.ACT
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
